### ISSUE TITLE
needs a block diagram

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCDeepSpace#1]
This project needs a block diagram to make it clear to team members what will be developed.

**Comment by snowpuppy** [comment]
There's a drawing on the whiteboard, but not all of the robot details have been finalized, so I'll leave this one open.

**Comment by tm1287** [comment]
Now that we are in week 6 and the robot does not seem subject to change, is this issue resolved?

**Comment by snowpuppy** [comment]
Yeah. We can say this is resolved now. In this case, the robot whiteboard drawing counts as a block diagram. 
https://raw.githubusercontent.com/Team1100/FRCDeepSpace/master/doc/images/Subsystem_Diagram_1.JPG
