### ISSUE TITLE
Robot exceeds 20ms timed intreval when executing vision PID command

### ISSUE THREAD

**Issue by tm1287** [Team1100/FRCDeepSpace#20]
# How To Replicate
Add one of the vision PID commands to be triggered when a button on the joystick gets pressed.

# Symptoms
Robot reports that watchdog has not been fed in 20ms
Robot reports that one or more processes has exceeded 20ms
Robot disables itself

# Possible Causes
Communication between robot and Raspberry Pi timing out?
Vision processing on Raspberry Pi taking to long?
Threading somehow messed up on the Pi?

**Comment by snowpuppy** [comment]
I'll take a look at your commands. This means that you're command is running too long without yielding. The watchdog timer is there to make sure that the software doesn't get stuck spinning its wheels forever.

**Comment by snowpuppy** [comment]
I don't immediately see the problem. Is there more output that you can post?

Any threads or vision processing on the Pi should not affect the watchdog timer on the RoboRio.

If NetworkTables for some reason took a long time to return with the values, then perhaps its NetworkTables, but I'm pretty sure part of the point of NetworkTables is that its asynchronous.

**Comment by Pentation** [comment]
@tm1287 Just push your bug-fixed code and we can close this
