### ISSUE TITLE
Timer shouldn't be started in constructor of command

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCDeepSpace#21]
https://github.com/Team1100/FRCDeepSpace/blob/f1c7df4e8c514e2f11116d7777730ec4fc3b266f/src/main/java/frc/robot/commands/vision/CenterRobot.java#L34

A timer shouldn't be started in the constructor of a command because the constructor is executed when the command is created, not when it should be run.

**Comment by tm1287** [comment]
Resolved. See commit 17f8f91
