### ISSUE TITLE
Bad logic in vision command group will not work as written

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCDeepSpace#35]
https://github.com/Team1100/FRCDeepSpace/blob/9acb37f3adf1592c5ca14817992fce1a66265415/src/main/java/frc/robot/commands/gantry/VisionGantryAlign.java#L1

The VisionGantryAlign command group will not run as written because the constructor will never terminate, thus no commands will be executed. This may set off the watchdog timer.

**Comment by tm1287** [comment]
Resolved.
