### ISSUE TITLE
brainstorm commands for ball intake

### ISSUE THREAD

**Issue by andrewyang89** [Team1100/FRCDeepSpace#5]

**Comment by Pentation** [comment]
Classes / Commands:

IntakeUp
IntakeDown
PushBallOut
PullBallIn
LiftRobot

1 motor to rotate intake
2 motors to control rollers
1 possible additional motor for winch for climbing

**Comment by Pentation** [comment]
Also: 1 pressure sensor (which we need)

**Comment by snowpuppy** [comment]
It could be a pressure sensor or a beam break sensor, probably the latter.

I left a beam break sensor in the programmer area with a note.

**Comment by Pentation** [comment]
Added Skeletal Files

**Comment by Pentation** [comment]
We also need another command to spit the ball out into the manipulator

**Comment by Pentation** [comment]
And we will have 1 motor to control rollers, not two

(Per Jason As of this comment)
