### ISSUE TITLE
brainstorm commands for elevator

### ISSUE THREAD

**Issue by andrewyang89** [Team1100/FRCDeepSpace#7]

**Comment by Pentation** [comment]
Commands:

DefaultElevator (manual control)
7 Auto-Specific Points for the Elevator: (AutoRocketHatchL1/2/3; AutoRocketCargoL1/2/3; FullCollapse)

2+ Limit Switches
2 motors
1 additional motor for climbing is possible

**Comment by Pentation** [comment]
Elevator will not go under robot
